sonar.projectKey=GabsDaArte_ES2_2025-2_Zettlr
sonar.organization=gabsdaarte

sonar.sources=.

sonar.exclusions=**/node_modules/**,**/dist/**,**/out/**

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
