# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Configurar GitHub Actions  

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Instalar Dependências
      run: npm ci
        
    - name: Executar Testes
      run: npm test
        
    - name: Empacotar Aplicação
      run: npm run package
      
    - uses: actions/upload-artifact@v4 # Use a v4, que é a mais recente
      if: success() || failure() # Publica o artefato mesmo se houver falha de teste/package
      with:
        name: zettlr-package-${{ matrix.os }}-${{ matrix.node-version }}
        path: out/ 
        retention-days: 5
